### ISSUE TITLE
Feature request: Disable Github job status in PR when enable `update_pull_request_status`

### ISSUE THREAD

**Issue by henrywang** [sclorg/testing-farm-as-github-action#129] opened 2024-03-07 06:01 UTC
When enabled `update_pull_request_status`, there're will be two job status in PR for the same test. One is from github job status, the other is from testing farm status. It'll be better to add one option to disable github job status and only keep testing farm status?

The github job status doesn't have testing farm log/result URL (`http://artifacts.osci.xxxx.xxx/testing-farm/uuid/`) included. And keeping two job status for the same test does not make sense.

Thanks!

**Comment by zmiklank** [comment] 2024-03-07 16:02
Hi, what trigger do you use for testing-farm-as-github-action?

**Comment by henrywang** [comment] 2024-03-08 03:29
> Hi, what trigger do you use for testing-farm-as-github-action?

I use `pull_request_target` event to trigger.
```yaml
pull_request_target:
    types: [opened, synchronize, reopened]
```

**Comment by zmiklank** [comment] 2024-03-22 13:03
> I use pull_request_target event to trigger.

I think I understand what you mean now.
I do not like this current behavior either, we bumped into it about a year ago, when we wanted to do a migration from issue_coment to pull_request[_target] trigger in sclorg.

So I think we can start from adding a **safe** [integration test](https://github.com/sclorg/testing-farm-as-github-action/pull/139), which would serve as very simple pull_request/pull_request_target trigger. Then we will have good reproducer.

**Comment by zmiklank** [comment] 2024-05-03 06:54
And also I think this feature request is duplicate of https://github.com/sclorg/testing-farm-as-github-action/issues/54.

**Closed by zmiklank** 2024-05-03 06:54 UTC
Labels: type: feature
